import "./globals.css";
import Navbar from "./components/navbar/Navbar";
import Footer from "./components/footer/Footer"
import MobileNavbar from "./components/mobileNav/MobileNavbar"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="max-w-screen-2xl m-auto font-[400]">
        <Navbar />
        {children}
        <Footer />
        <MobileNavbar />
      </body>
    </html>
  );
}
